version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-243-208-234.compute-1.amazonaws.com
            port: '5432'
            database: d1b1h0n9ho5g12
            ssl: true
            user: bsiucdedxeahvl
            password: 5fad305b75228065de102128e41e10f4f67b89322bd8ddde216b6866fd613d66
            migrations: true